name: luonnosta_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.8+10

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  package_info_plus: ^4.0.2
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  pdf: ^3.8.4
  printing: ^5.9.3
  path_provider: ^2.0.11
  open_file: ^3.2.1
  json_annotation: ^4.7.0
  http: ^0.13.5
  image_picker: ^1.0.0
  firebase_storage: ^11.0.9
  uuid: ^3.0.7
  vector_map_tiles: ^4.0.0
  proj4dart: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/image/
    - assets/licenses/

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/font/Questrial-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/font/MontserratRegular400.ttf
 